### ISSUE TITLE
Would like to use 1.9.X Stable

### ISSUE THREAD

**Issue by JREAM** [codezeus/django-project-template#1]
I have upgraded from 8 to 9 without any problems on a lesson I'm building, any thoughts?

**Comment by dansackett** [comment]
I'd say once it reaches rc1 or rc2 we should switch to 1.9. Alpha is early for me. Let's keep this open until then.

**Comment by JREAM** [comment]
Yup you are right, my mistake I went from 1.7 to 1.8 stable, lets wait.
